apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: employee-management

spec:
  selector:
    app: employee-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort
